// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKzeaSdGrYox8Zy61K-LoORQQ8p-Uwc4',
    appId: '1:594396643941:android:9046f060b1a830479e7c8c',
    messagingSenderId: '594396643941',
    projectId: 'crud-flutter-tutorial',
    storageBucket: 'crud-flutter-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtvqv1lFeo8hW2Pe3UNk8Hqey2cYl3XU',
    appId: '1:594396643941:ios:84e1419651030b5a9e7c8c',
    messagingSenderId: '594396643941',
    projectId: 'crud-flutter-tutorial',
    storageBucket: 'crud-flutter-tutorial.appspot.com',
    androidClientId: '594396643941-ee5mu7kem6mlmpej8nlfdps8cs72n6ic.apps.googleusercontent.com',
    iosClientId: '594396643941-uqcueousmu3mrj62676t07ior3uv60dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
